class_name: Sequential
config:
- class_name: Dense
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    batch_input_shape: !!python/tuple [null, 8]
    bias: true
    init: uniform
    input_dim: 8
    input_dtype: float32
    name: dense_210
    output_dim: 12
    trainable: true
- class_name: Dense
  config: {W_constraint: null, W_regularizer: null, activation: relu, activity_regularizer: null,
    b_constraint: null, b_regularizer: null, bias: true, init: uniform, input_dim: null,
    name: dense_211, output_dim: 8, trainable: true}
- class_name: Dense
  config: {W_constraint: null, W_regularizer: null, activation: sigmoid, activity_regularizer: null,
    b_constraint: null, b_regularizer: null, bias: true, init: uniform, input_dim: null,
    name: dense_212, output_dim: 1, trainable: true}
keras_version: 1.0.5
loss: binary_crossentropy
optimizer: {beta_1: 0.8999999761581421, beta_2: 0.9990000128746033, epsilon: 1.0e-08,
  lr: 0.0010000000474974513, name: Adam}
sample_weight_mode: null
